apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: worldcup
data:
  POSTGRES_DB: football_db       
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: worldcup
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/football_db
  FASTAPI_URL: http://ml-service:8000
