#Connecting to the DB on our docker container
spring.datasource.url=jdbc:postgresql://localhost:5433/football_db
spring.datasource.username=springuser
spring.datasource.password=springpassword
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernete confiuguration
#Currently on create-drop until evrerything is set
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Showing the sql logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
fastapi.url=http://localhost:8000
spring.sql.init.mode=always